# Generated by Django 2.1 on 2018-09-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='auth_user_profile',
        ),
    ]
