# Generated by Django 2.1 on 2018-09-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20180914_1731'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='auth_user_profile',
        ),
    ]
