# Generated by Django 2.1 on 2018-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_profile_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kakao_passwd',
            field=models.CharField(default='lcventures', max_length=128),
            preserve_default=False,
        ),
    ]
