# Generated by Django 2.1 on 2018-08-27 17:24

import Reply.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='type',
            field=enumfields.fields.EnumField(default='0', enum=Reply.models.Type, max_length=1),
        ),
    ]
