# Generated by Django 2.1 on 2018-08-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reply', '0002_reply_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='channel',
        ),
    ]
