# Generated by Django 2.1 on 2018-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reply', '0003_remove_reply_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
