# Generated by Django 2.1 on 2018-08-27 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(max_length=50)),
                ('channel_e_title', models.CharField(max_length=50)),
                ('channel_thumbnail_url', models.CharField(max_length=256)),
                ('channel_news_count', models.IntegerField()),
                ('channel_subscriber_count', models.IntegerField()),
                ('channel_visitor_count', models.IntegerField()),
                ('channel_activity_users_count', models.IntegerField()),
                ('channel_url', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Channel',
            },
        ),
    ]
